# Generated by Django 4.0.5 on 2022-11-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rforce', '0005_demofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demofile',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
    ]
